OPENAI_MODEL = "gpt-5.4-mini"
OPENAI_MAX_OUTPUT_TOKENS = 6000

GITHUB_API_ACCEPT_HEADER = "application/vnd.github.v3+json"
GITHUB_TREE_BRANCH = "HEAD"
MAX_KOTLIN_FILES = 20
MAX_CODE_CHARS_FOR_PROMPT = 8000
